---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: nopwd
spec:
  encryptedData:
    .dockerconfigjson: AgCmZ7mCA/q8oQUwXBcmRQqLmtekgyQ+lrezknd/A6NRNegV1AVcjz5GIlIfaIyE6uruGVbWbK5vk7Bb6c8UBIoQKnN5n0A5SG3InuvqE75XxGODzYHDub0Eq9jczPPQ2F/vnKK0/7BV830eBzjKAtZrwejnjs0l0NeVxlrWd61u5PM+SSgOKV5tr45iJgKB67Ld9GxDd5EG2pgbG4YwkqmXuNf2XVTQsy5AemIyG+yleDNS5HDvl8tH/hK5SYnxLb4AvhkEv9vhJIywZ8hEYfohYfhW2PrbeEMk6PK/YtB41oWgwrETZQOpqV+V8DqqYP+yAJIyg7Hv4ecX19WNzgKmKOw6QVUlIMGx0APqpZzmXGuJ2hIAwLh99Fm77jxTHJb3XlB1PBoS2uWIe8Gw+omuDSNp5RaZrK49O5n241rZ5j+R/J3x4aCt36aBjv8bThRB4yWv39onyQ9zxzFkCTagDBDaBKK9KmzSTljVUqJTAfOMzPUgX1dGTqZQ7m8j/BwkhroZXkBbX4dAfQ6Q47Lfc3ePuUyOkGFp4Y3608cAGrcdtNA0gKr7vhd7Bu/4XbuFnMvRFJ60E/plNx5tnq/dfFUL8Sq8unIi64aOr8ZOZLEzhwoyNQnJ1U1IBymwOtVVAgF+7nq7VqldNMbpH4DAEqbEqiukwxdT60HxEKbEGOkVv3V0ooeumw43ZTCRNpXr1WHoFXd4ROr0ulkGs9AezwfBkXXHFq1mK7mfpUhahWUp55reTRQF1hSw0rK8+Izqq0RJe8MgmJwJXJz/OznF/vCqdOpmEZZnnNtJRNCDVcBTzZLTH0ggnlXocy8Q/sclCGeUuY7slwZOWvFE6Q03sDWAQ44qX6yIredOwgKZe1Tjn+yer5X492EtUjD60Ol7gLrGTIS1ST9AKiSmkJIQ/jD4hNwgXuTWEUA35471aWDbAt29qpCL
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: nopwd
    type: kubernetes.io/dockerconfigjson
