apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - sealed-secret.yaml
  - api-deployment.yaml
  - web-deployment.yaml
  - services.yaml
  - ingress.yaml
  - poddisruptionbudget.yaml
