[package]
name = "nopass-crypto"
version.workspace = true
edition.workspace = true

[dependencies]
nopass-models = { path = "../nopass-models" }

argon2 = { workspace = true }
aes-gcm = { workspace = true }
hkdf = { workspace = true }
sha2 = { workspace = true }
hmac = { workspace = true }
zeroize = { workspace = true }
rand = { workspace = true }
hex = { workspace = true }
base64 = { workspace = true }
srp = { workspace = true }

serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
hex-literal = "0.4"
